// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijvonjmmxziwlrksxdtk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlqdm9uam1teHppd2xya3N4ZHRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NjYxMjUsImV4cCI6MjA2NTA0MjEyNX0.S_nysYaIZqhGsKomSs0Nsa6sFcfTrWjnBj7ZWPUdrfI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);